source 'https://github.com/CocoaPods/Specs.git'

target 'HIVendorManager_Example' do
  pod 'HIVendorManager', :path => '../'
  pod 'AMap3DMap'
  pod 'AMapLocation'
  pod 'AMapNavi'
#  pod 'AMapSearch'
end
